name: build
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build-linux:
    # If this was triggered by a pull request, only run it if it
    # originates from a fork.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != 'radicle-dev/radicle-upstream'
    runs-on: ubuntu-latest
    container:
      image: "gcr.io/opensourcecoin/radicle-upstream:0.9.0"
    steps:
      - uses: actions/checkout@master
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/yarn
            ~/cache/cypress
          key: build-${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            build-${{ runner.os }}-yarn-v1-
      - name: Cache Rust
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/cargo
            ~/cache/proxy-target
          key: build-${{ runner.os }}-rust-v1-${{ hashFiles('Cargo.lock') }}
      - run: ci/run.sh
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-artifacts
          path: |
            cypress/screenshots/**/*.png
            cypress/workspace/test-tmp/*/node-*/*.log
            cypress/workspace/test-tmp/*/combined-node.log
